### PR TITLE
Replace ansi_term with nu_ansi_term

### PR DESCRIPTION
**Pull request by sylvestre**
See : 
https://github.com/ogham/rust-ansi-term/issues/72

### CODE REVIEW

**Comment by sylvestre** [comment]
might requires a version bump as the feature has been renamed (i could try to keep)

**Comment by sharkdp** [comment]
Thank you for your contribution!

> [ogham/rust-ansi-term#72](https://github.com/ogham/rust-ansi-term/issues/72)

Hm, sad. Are the maintainers of `nu-ansi-term` advertising their project as a replacement that other can depend on? Or is it only ment for internal usage in nushell?

**Comment by fdncred** [comment]
> Hm, sad. Are the maintainers of nu-ansi-term ...

We're not advertising it but we plan to continue using it. We forked it to make some changes that you can see in the changelog on the nu-ansi-term repo. We only mess with it when we need something new in terms of ansi escape sequences.

A few people seem to be using it https://crates.io/crates/nu-ansi-term/reverse_dependencies

**Comment by sharkdp** [comment]
@fdncred Thank you!


@sylvestre There is no *need* to upgrade for downstream users of `lscolors`. Would it be possible to add `nu-ansi-term` as a new feature, in addition to the old variant? This would allow us to maintain backward compatibility.

Alternatively, would it be possible to introduce `nu-ansi-term` in a non-breaking way? By still calling the feature etc. the same as before? Any drawbacks in this approach?

**Comment by sylvestre** [comment]
@sharkdp does it match your expectations ? :)
thanks

**Review by sharkdp — APPROVED** [review]
Yes, thank you!

**Comment by sylvestre** [comment]
@sharkdp thank for the merge!
Would it be possible to have a new release of lscolors with this change ? :)

**Comment by sharkdp** [comment]
done.

**Comment by sylvestre** [comment]
many thanks :)

**Pull request merged**
