### PR TITLE
Add support for more indicators

### PR DESCRIPTION
**Pull request by tavianator**
Partially addresses #6.

- [x] Tests

### CODE REVIEW

**Comment by tavianator** [comment]
Hmm, the failed build is due to

>     could not find `stringify` in `_core`

**Comment by sharkdp** [comment]
Thank you very much for working on this! I'm hoping to find some time to review it soon.

I guess the build error is already present on `master`. Pretty sure I've seen this before. ~~Probably needs a MSRV upgrade.~~

**Comment by sharkdp** [comment]
From a rough view, this looks very good. I'd be happy to integrate this if we can add the missing tests.

**Comment by sharkdp** [comment]
I have migrated the project to GitHub Actions since Travis service has been discontinued. I rebased your branch. There is no build error anymore.

**Review by sharkdp — APPROVED** [review]
Awesome work - thank you very much!

**Pull request merged**
