### PR TITLE
Allow *.ext=0 to override an earlier *.ext=...

### PR DESCRIPTION
**Pull request by tavianator**

### CODE REVIEW

**Comment by sharkdp** [comment]
Oh nice, thank you!

I hope we are eventually converging to something that is 100% compatible with `ls`. Was somehow imagining this to be a smaller topic when I initially started out with this projecft :upside_down_face:.

**Comment by tavianator** [comment]
> I hope we are eventually converging to something that is 100% compatible with `ls`. Was somehow imagining this to be a smaller topic when I initially started out with this projecft upside_down_face.

Haha yeah there is a surprising amount of complexity to `LS_COLORS` :)

Maybe we should open a tracking issue to document the remaining incompatibilities?  There's at least

- `ln=target`: https://github.com/sharkdp/lscolors/issues/11
- `ca` and `do`: https://github.com/sharkdp/lscolors/issues/6
- `rs`, `lc`, `rc`, `ec`, `cl`: No specific issue for this, maybe https://github.com/sharkdp/lscolors/issues/2?  These let `ls` support non-ANSI terminals, e.g.
```console
$ LS_COLORS="rs=RESET :lc=LEFT :rc=RIGHT :ex=EXECUTABLE " ls ./target/debug/lscolors 
LEFT RESET RIGHT LEFT EXECUTABLE RIGHT ./target/debug/lscolorsLEFT RESET RIGHT 
LEFT RIGHT 
```

**Comment by tavianator** [comment]
Oh and escape sequences: https://github.com/tavianator/bfs/blob/33293e337ed4d9205b1185c44e1fe3fcb1a10af6/src/color.c#L197-L226

**Comment by sharkdp** [comment]
> Maybe we should open a tracking issue to document the remaining incompatibilities?

That would be great!

**Comment by tavianator** [comment]
Done: #48

**Pull request merged**
